Default: &defaults
  user: widefield
  password: widefield
  host: reichardt.uoregon.edu
  database: widefield
  connections: 10

Development:
  <<: *defaults

Testing:
  database: ytm_test
  <<: *defaults

Staging:
  database: ytm_staging
  connections: 100
  <<: *defaults

Production:
  database: ytm_production
  connections: 100
  host: localhost
  <<: *defaults
